# Generated by Django 5.0.4 on 2024-04-07 05:19

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Question')),
                ('question_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='question')),
                ('question_category', models.CharField(choices=[('what', 'what'), ('why', 'why'), ('how', 'how')], max_length=50, verbose_name='Choices')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
