# Generated by Django 5.0.4 on 2024-04-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_question_answer_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_category',
            field=models.CharField(choices=[('what', 'what'), ('why', 'why'), ('how', 'how'), ('is', 'is')], max_length=50, verbose_name='Choices'),
        ),
    ]
