# Generated by Django 5.0.4 on 2024-04-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_video_country_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='country_code',
            new_name='trending_cc',
        ),
    ]
