# Generated by Django 5.0.4 on 2024-04-14 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_country_code_video_trending_cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='trending_cc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.country', to_field='country_code', verbose_name='Country Code'),
        ),
    ]
