# Generated by Django 5.0.4 on 2024-04-10 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_question_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_history',
        ),
        migrations.CreateModel(
            name='HistoricResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_history', models.JSONField(default=dict, verbose_name='Answers History')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'HistoricResult',
                'verbose_name_plural': 'HistoricResults',
            },
        ),
    ]
