# Generated by Django 5.0.4 on 2024-04-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_video_trending_cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='last_updated',
            field=models.DateField(auto_now_add=True, verbose_name=''),
        ),
    ]
