# Generated by Django 5.0.4 on 2024-04-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_question_answer_history_historicresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicresult',
            options={'verbose_name': 'Historic Result', 'verbose_name_plural': 'Historic Results'},
        ),
        migrations.AddField(
            model_name='question',
            name='latest_answer',
            field=models.TextField(default='', verbose_name='Latest Answer'),
        ),
    ]
