# Generated by Django 5.0.4 on 2024-04-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_historicresult_options_question_latest_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.DeleteModel(
            name='HistoricResult',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
