# Generated by Django 5.0.4 on 2024-04-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_video_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='last_updated',
        ),
    ]
