# Generated by Django 5.0.4 on 2024-04-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_video_video_api_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date_fetched',
            field=models.DateField(default=None, unique=True, verbose_name='Fetched on:'),
        ),
    ]
