# Generated by Django 5.0.4 on 2024-04-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_video_date_fetched'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='country_code',
            field=models.CharField(default=None, max_length=2, verbose_name='Country Code'),
        ),
    ]
