# Generated by Django 5.0.4 on 2024-04-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_video_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='country_name',
            field=models.CharField(default=None, max_length=100, verbose_name='Country Name'),
        ),
    ]
