# Generated by Django 5.0.4 on 2024-04-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_video_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date_fetched',
            field=models.DateField(default=None, verbose_name='Fetched on:'),
        ),
    ]
