# Generated by Django 5.0.4 on 2024-04-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_video_date_fetched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='country_code',
            field=models.CharField(choices=[('AL', 'Albania'), ('AE', 'United Arab Emirates'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BE', 'Belgium'), ('BD', 'Bangladesh'), ('BG', 'Bulgaria'), ('BH', 'Bahrain'), ('BA', 'Bosnia and Herzegovina'), ('BY', 'Belarus'), ('BO', 'Bolivia, Plurinational State of'), ('BR', 'Brazil'), ('CA', 'Canada'), ('CH', 'Switzerland'), ('CL', 'Chile'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CY', 'Cyprus'), ('CZ', 'Czechia'), ('DE', 'Germany'), ('DK', 'Denmark'), ('DO', 'Dominican Republic'), ('DZ', 'Algeria'), ('EC', 'Ecuador'), ('EG', 'Egypt'), ('ES', 'Spain'), ('EE', 'Estonia'), ('FI', 'Finland'), ('FR', 'France'), ('GB', 'United Kingdom'), ('GE', 'Georgia'), ('GH', 'Ghana'), ('GR', 'Greece'), ('GT', 'Guatemala'), ('HK', 'Hong Kong'), ('HN', 'Honduras'), ('HR', 'Croatia'), ('HU', 'Hungary'), ('ID', 'Indonesia'), ('IN', 'India'), ('IE', 'Ireland'), ('IQ', 'Iraq'), ('IS', 'Iceland'), ('IL', 'Israel'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JO', 'Jordan'), ('JP', 'Japan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('KH', 'Cambodia'), ('KR', 'Korea, Republic of'), ('KW', 'Kuwait'), ('LA', "Lao People's Democratic Republic"), ('LB', 'Lebanon'), ('LY', 'Libya'), ('LI', 'Liechtenstein'), ('LK', 'Sri Lanka'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('LV', 'Latvia'), ('MA', 'Morocco'), ('MD', 'Moldova, Republic of'), ('MX', 'Mexico'), ('MK', 'North Macedonia'), ('MT', 'Malta'), ('ME', 'Montenegro'), ('MN', 'Mongolia'), ('MY', 'Malaysia'), ('NG', 'Nigeria'), ('NI', 'Nicaragua'), ('NL', 'Netherlands'), ('NO', 'Norway'), ('NP', 'Nepal'), ('NZ', 'New Zealand'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PA', 'Panama'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PG', 'Papua New Guinea'), ('PL', 'Poland'), ('PR', 'Puerto Rico'), ('PT', 'Portugal'), ('PY', 'Paraguay'), ('QA', 'Qatar'), ('RO', 'Romania'), ('RU', 'Russian Federation'), ('SA', 'Saudi Arabia'), ('SN', 'Senegal'), ('SG', 'Singapore'), ('SV', 'El Salvador'), ('RS', 'Serbia'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('SE', 'Sweden'), ('TH', 'Thailand'), ('TN', 'Tunisia'), ('TR', 'Türkiye'), ('TW', 'Taiwan, Province of China'), ('TZ', 'Tanzania, United Republic of'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('UY', 'Uruguay'), ('US', 'United States'), ('VE', 'Venezuela, Bolivarian Republic of'), ('VN', 'Viet Nam'), ('YE', 'Yemen'), ('ZA', 'South Africa'), ('ZW', 'Zimbabwe')], default=None, max_length=2, verbose_name='Country Code'),
        ),
    ]
