# Generated by Django 5.0.4 on 2024-04-14 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_remove_video_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.country', to_field='country_code', verbose_name='Country Code'),
        ),
    ]
