# Generated by Django 5.0.4 on 2024-04-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_video_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date_fetched',
            field=models.DateField(db_index=True, default=None, verbose_name='Fetched on:'),
        ),
    ]
