# Generated by Django 5.0.4 on 2024-04-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_alter_video_date_fetched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='country',
            new_name='country_code',
        ),
    ]
